apiVersion: v1
kind: Service
metadata:
  name: todoapp
spec:
  selector:
    app.kubernetes.io/instance: todoapp
    app.kubernetes.io/name: todoapp
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: http-metrics
      port: 8080  # Update this port to match the metrics port
      targetPort: 8080
  type: ClusterIP
